# Generated by Django 2.1.5 on 2019-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190309_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasks',
            name='task_comments',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
